apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-capstone-deployment
  labels:
    app: pp-capstone-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pp-capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pp-capstone-deployment
    spec:
      containers:
        - image: prayon/pp-capstone
          imagePullPolicy: Always
          name: pp-capstone-deployment
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pp-capstone-svc
  labels:
    app: pp-capstone-deployment
spec:
  type: LoadBalancer
  selector:
    app: pp-capstone-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
